### ISSUE TITLE
What should be the format for added events? 

### ISSUE THREAD

**Issue by gustojs** [VueMeetups/vuemeetups.org#47]
What should be the format for added events? 

I'd suggest dropping the month name from each line, because right now it gets more accented than the town's name and it's redundant since each month has a separate headline.

Also, how to make the town more visible?

**Comment by bencodezen** [comment]
@gustojs Great question. I've been debating this for some time as well. I like your suggestion as an improvement on the current format.

**Comment by bencodezen** [comment]
@gustojs Going to close this issue since we have a new format for adding events. Thanks to great work by @atrunelle, it's now managed in a JSON file that is automatically output to the page. 

The next steps will be to automatically generate the file, but I think we are taking a step in the right direction!
